### ISSUE TITLE
Unable to mount Nfs Volume

### ISSUE THREAD

**Issue by abhilashdk2016** [phcollignon/kubernetes_storage#1]
Hi,

When I try to run kubectl apply -f busybox-nfs.yaml the pods are not creating due the following error:
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    156m                  default-scheduler  Successfully assigned default/busybox-75bbf554bd-5q8kz to docker-desktop
  Warning  FailedMount  151m (x2 over 154m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[nfs], unattached volumes=[nfs kube-api-access-dfdpx]: timed out waiting for the condition
  Warning  FailedMount  150m (x11 over 156m)  kubelet            MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs nfs-server:/exports /var/lib/kubelet/pods/ee25851f-b837-47e2-9619-6d875b9a0a44/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Failed to resolve server nfs-server: Name or service not known
  Warning  FailedMount  149m                kubelet  Unable to attach or mount volumes: unmounted volumes=[nfs], unattached volumes=[kube-api-access-dfdpx nfs]: timed out waiting for the condition
  Warning  FailedMount  42s (x8 over 106s)  kubelet  MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs nfs-server:/exports /var/lib/kubelet/pods/ee25851f-b837-47e2-9619-6d875b9a0a44/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Failed to resolve server nfs-server: Name or service not known

The same error with minikube (Ubuntu 20.04) too.  

<img width="1680" alt="Screenshot 2021-08-01 at 12 42 30 AM" src="https://user-images.githubusercontent.com/16358319/127750228-5369e91b-ea6d-4831-8170-76f0fe4ee755.png">

Could you please help me how to resolve this.

Thanks in advance.

<img width="1680" alt="Screenshot 2021-08-01 at 12 39 54 AM" src="https://user-images.githubusercontent.com/16358319/127750165-a6a759d9-9e90-4feb-a36f-31e119763eff.png">

**Comment by phcollignon** [comment]
Hello,
Did you add nfs-server container to the docker network ?
(`docker network connect minikube nfs-server `)
If so, can you log to minikube (`minikube ssh`) and run (`nslookup nfs-server`) and give me the result.
Thanks,
Philippe

**Comment by abhilashdk2016** [comment]
Hello Philippe,

Thanks for the reply. Yes i added the nfs-server container to the docker network. Here is the logs from `nslookup nfs-server`
```
Server:		192.168.49.1
Address:	192.168.49.1#53

Non-authoritative answer:
Name:	nfs-server
Address: 192.168.49.3
```
I get the following error now :
<img width="1680" alt="Screenshot 2021-08-01 at 9 00 30 PM" src="https://user-images.githubusercontent.com/16358319/127776602-763c20d6-1d3d-4416-99d0-5bea50f44c44.png">

Thanks,
Abhilash D K

**Comment by phcollignon** [comment]
Everything looks fine in the name resolution now (which was the first error)

Now I don't know why the mount fails .. does the export directory volume exists on the host with full right access ?
(`ls -al /var/nfs` by default)

**Comment by abhilashdk2016** [comment]
Yes Philippe. I do have full access to /var/nfs
```
ls -al /var/nfs
total 8
drwxr-xr-x  2 root root 4096 Jul 31 11:31 .
drwxr-xr-x 15 root root 4096 Jul 31 11:31 ..

```

**Comment by phcollignon** [comment]
Can you change the write access to writable for all.
And test again.  (minikube delete, delete container and install again also)

Which version of docker are you using ? Which version of minikube ?
I've just tested on debian 10 with minikube 1.18.1 and docker 18.09.1 and it's working.
I'll try to reproduce on ubuntu 20.4 and same versions you are using

**Comment by abhilashdk2016** [comment]
Changed the permission to all using the below command:
`sudo chmod ugo+rwx /var/nfs`
```
docker --version
Docker version 20.10.7, build f0df350

```
```
minikube version
minikube version: v1.22.0
commit: a03fbcf166e6f74ef224d4a63be4277d017bb62e
```

All latest version. Uubuntu and all softwares is a fresh install.  Will reinstall and update.

**Comment by abhilashdk2016** [comment]
Hi Philippe,
Here are the commands I used after deleting minikube and the container.
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
minikube start
ls -al /var/nfs
docker run -d --rm --privileged --name nfs-server  -v /var/nfs:/var/nfs  phico/nfs-server:latest
docker network connect minikube nfs-server
```
```
kubectl apply -f busybox-nfs.yaml 
kubectl get pods
kubectl describe pod busybox-7b66d94df5-52589
```
<img width="1680" alt="Screenshot 2021-08-01 at 10 32 29 PM" src="https://user-images.githubusercontent.com/16358319/127779349-385eafd5-09a6-4325-8ed8-a18a15922499.png">

I will try in Ubuntu 18 with docker and minikube same version as you are using.

**Comment by phcollignon** [comment]
You run the right commands .. strange.

Could you login to minikube (`minikube ssh`) and check that nfs-common is installed (`apt list | grep nfs`)  ?

**Comment by abhilashdk2016** [comment]
```
docker@minikube:~$ apt list | grep nfs

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnfsidmap2/now 0.25-5.1ubuntu1 amd64 [installed,local]
nfs-common/now 1:1.3.4-2.5ubuntu3.4 amd64 [installed,local]
```
It's installed :(

**Comment by phcollignon** [comment]
Did you build the nfs-server image yourself? or use the docker hub one ?
I've pushed my latest image, try to delete your nfs-server container and image and install it again.

**Comment by abhilashdk2016** [comment]
I used your nfs-server image itself and did not build it myself. I deleted the existing image and got new image.

```
docker run -d --rm --privileged --name nfs-server  -v /var/nfs:/var/nfs  phico/nfs-server:latest
Unable to find image 'phico/nfs-server:latest' locally
latest: Pulling from phico/nfs-server
62deabe7a6db: Pull complete 
42f6f55d78fb: Pull complete 
1fed7019e0f3: Pull complete 
1ecc60606e7f: Pull complete 
91cca14d88b0: Pull complete 
02dd18193e20: Pull complete 
Digest: sha256:70fbebd476bcb9eebceaa84387e08079ee8457e8d63fcd9d3d4d5aea63ed76d7
Status: Downloaded newer image for phico/nfs-server:latest
0ccb5eff0547d27f2c11cd2b9c7ab187968679ecad350bf501fa01aa040141d9
docker network connect minikube nfs-server
```
No luck :(

<img width="1614" alt="Screenshot 2021-08-02 at 12 22 35 AM" src="https://user-images.githubusercontent.com/16358319/127782145-07023113-e4b7-47cc-bf5c-075ab16473ab.png">

**Comment by phcollignon** [comment]
Basic question but minikube is well running with docker driver ?
Try` docker ps` to see if there is a minikube container and ` docker network ls` to see if there is a minikube network.

I begin to try in ubuntu with latest docker and minikube versions.

**Comment by phcollignon** [comment]
I tried on Ubuntu 20.4 with docker 20.10.7 and minikube 1.22 and could get it working
but I had to install nfs-server and nfs-common packages on the host before running the nfs-server container.
(it looks like that the kernel is missing nfs module to run the nfs-server in the container)
So run this on your host :
``` 
sudo apt-get install nfs-common
sudo apt-get install nfs-server
``` 
Then delete the nfs-container.  Delete the /var/nfs folder.  Restart the nfs-server container and it should work !

**Comment by abhilashdk2016** [comment]
Hi Philippe,

minikube is running on docker driver itself.

After installing nfs-common and nfs-server It's working. 

<img width="1614" alt="Screenshot 2021-08-02 at 9 53 58 AM" src="https://user-images.githubusercontent.com/16358319/127804068-475bbdf9-a142-41a1-ba7f-3703315f17c0.png">


Thank you very much for your time :)

**Comment by phcollignon** [comment]
Good news !
And what about macos ? 
If you add nfs support to the kernel it should also work. (I'm not a mac user .. but it should be something like `modprobe nfs
modprobe nfsd` ?? )

**Comment by abhilashdk2016** [comment]
modeprobe is not available in macos. When I run nfsd status. It says enabled and running. But nfs is not available. I am Scouring the internet to see how to enable nfs mounts. Will update once I am able to find a solution for mac.

**Comment by phcollignon** [comment]
You can try to make the container loading the modules for you that way : https://github.com/ehough/docker-nfs-server/blob/develop/doc/feature/auto-load-kernel-modules.md but not sure this works on macos

**Comment by abhilashdk2016** [comment]
I tried the below commands directly. But no progress. Will try to use the compose file you suggested and update.
<img width="1614" alt="Screenshot 2021-08-02 at 2 58 10 PM" src="https://user-images.githubusercontent.com/16358319/127838563-3b385ed6-6804-4b21-85cb-bcf213542500.png">

**Comment by abhilashdk2016** [comment]
I am using the provided docker-compose file but did some changes like below:
```
version: "3"
services:
  nfs:
    image: erichough/nfs-server
    volumes:
      - /var/nfs:/nfs
      - /lib/modules:/lib/modules:ro
    environment: 
     - NFS_EXPORT_0='/var/nfs                  *(ro,no_subtree_check)'
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    ports:
      - 2050:2049
```

And I am getting below error.
<img width="1614" alt="Screenshot 2021-08-02 at 3 19 30 PM" src="https://user-images.githubusercontent.com/16358319/127842124-7aa457ed-9d9c-4374-a1a2-7b6e98c91801.png">

**Comment by phcollignon** [comment]
That one is using another image ..  the idea was to use the same cap_add and volume mapping with my image phico/nfs-server.

I'll git it a try but I cannot put this as default as it modifies some host files, I don't want to modify users host's config without consent

**Comment by abhilashdk2016** [comment]
I used the below command

```
docker run -d --rm --privileged --cap-add SYS_ADMIN --name nfs-server -v /var/nfs:/var/nfs -v /lib/modules:/lib/modules:ro phico/nfs-server:latest
```

The logs from the container are:

```
mkdir: cannot create directory '/var/nfs/exports': Operation not permitted

chmod: cannot access '/var/nfs/exports': No such file or directory


Starting NFS server ...

Not starting NFS kernel daemon: no support in current kernel. ... (warning).

NFS server started and listening on 172.17.0.2
```
Obtaining this error now.
```
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    2m46s  default-scheduler  Successfully assigned default/busybox-7f68fb9466-bb59x to minikube
  Warning  FailedMount  44s    kubelet            Unable to attach or mount volumes: unmounted volumes=[nfs], unattached volumes=[nfs kube-api-access-dclqb]: timed out waiting for the condition
  Warning  FailedMount  35s    kubelet            MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 172.17.0.3:/exports /var/lib/kubelet/pods/46d8ec4b-4a48-4945-b905-7ee50ec7f1fe/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Connection timed out
```

One thing I noticed here is NFS Server is listening on 172.17.0.2 but in container logs it's trying to connect to 172.17.0.3.

**Comment by phcollignon** [comment]
Yes that's the command I was thinking about. (unfortunately I have no mac to test ..) 
Can you try with another docker volume .. maybe macos prevents you to create exports in /var/nfs (i.e.  `-v /tmp/nfs:/var/nfs  ` ) or chmod the directory.

**Comment by abhilashdk2016** [comment]
I changed docker volume to /tmp/nfs. No luck.

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    11m                   default-scheduler  Successfully assigned default/busybox-7f68fb9466-qd9cr to minikube
  Warning  FailedMount  2m11s (x4 over 9m2s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[nfs], unattached volumes=[nfs kube-api-access-dr7tr]: timed out waiting for the condition
  Warning  FailedMount  2s (x5 over 8m53s)    kubelet            MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 172.17.0.3:/exports /var/lib/kubelet/pods/d267e8d4-a53a-475b-bd92-3a06d0171dc1/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Connection timed out
```

**Comment by phcollignon** [comment]
Then, you can try to launch the container without volume, but you'll have to list the files in the container rather than on the host : 
(  `docker exec nfs-server cat /var/nfs/exports/log.txt` instead of `cat /var/nfs/exports/log.txt` )
Or you just use a Linux VM on macOS ..

**Comment by abhilashdk2016** [comment]
Yes Philippe. I will go ahead with Linux VM. Thank you for helping me out :)
